#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

BRANCH=$(git rev-parse --abbrev-ref HEAD | grep -o '[A-Z]*-[0-9]*' | head -1)
grep -qs "^$BRANCH" "$COMMIT_MSG_FILE" || echo "[$BRANCH] $(cat $COMMIT_MSG_FILE)" > "$COMMIT_MSG_FILE"
